spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  sessionToken: ${AWS_SESSION_TOKEN}
  region: us-east-1